# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build & Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node v13.13 and install dependencies
      uses: actions/setup-node@v1
      with:
        node-version: "13.13"
    - name: Run CI, tests, and build
      run: |
        npm ci
        npm test
        npm run build
        mv docs daily
    - name: Deploy to ODI Webserver
      uses: appleboy/scp-action@v0.0.1
      env: 
        HOST: ${{ secrets.HOST }}
        PORT: 22
        USERNAME: "odi"
        KEY: ${{ secrets.KEY }}
        SOURCE: "daily"
        TARGET: "/home/odi/www/odileeds.org/projects/flight-emissions/"
        OVERWRITE: true

        

