# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node v13.13 and install dependencies
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Sync
      env:
        dest: 'odi@onza.mythic-beasts.com:/home/odi/www/odileeds.org/projects/flight-emissions/daily/'
      run: |
        echo "${{secrets.DEPLOY_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -av --delete -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' ./docs/ ${{env.dest}}
        rm -f deploy_key

        

